WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication3/Controllers/ITController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing.Printing;

namespace WebApplication3.Controllers
{
    public class ITController : Controller
    {
        [HttpGet]
        // GET: Tests
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ITTools()
        {
            return View();
        }
        public ActionResult FormMethod(string name, int nombre)
        {

            string Message = string.Format($"Hello, {name} and {nombre}");
            ViewBag.Go = string.Format($"Hello, {name} and {nombre}");

            return View("ITTools");
        } 
    }
}

WebApplication3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    .container {
        width: 60% !important
    }
</style>

<div class="jumbotron">
    <h1>IT Web App</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<figure class="highlight">
    <pre><code class="language-scss" data-lang="scss"><span class="c1">// Extra small devices (portrait phones, less than 576px)</span>
    <span class="c1">// No media query since this is the default in Bootstrap</span>
    <span class="c1">// Small devices (landscape phones, 576px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">576px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Medium devices (tablets, 768px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">768px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Large devices (desktops, 992px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">992px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Extra large devices (large desktops, 1200px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">1200px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>
</code></pre>
</figure>
<div class="alert alert-danger" role="alert">
    This is a danger alert—check it out!
</div>
<p>Welcome</p>
<figure class="highlight">
    <pre><code class="language-scss" data-lang="scss"><span class="c1">// Extra small devices (portrait phones, less than 576px)</span>
    <span class="c1">// No media query since this is the default in Bootstrap</span>

    <span class="c1">// Small devices (landscape phones, 576px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">576px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Medium devices (tablets, 768px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">768px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Large devices (desktops, 992px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">992px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Extra large devices (large desktops, 1200px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">1200px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span></code></pre>
</figure>

<p>Since we write our source CSS in Sass, all our media queries are available via Sass mixins:</p>

WebApplication3/Views/IT/ITTools.cshtml
@{
    ViewBag.Title = "Outils IT";
}
<style>
    .container {
        width: 60% !important
    }
</style>
<h3>@ViewBag.Title</h3>

<pre><code><img src="@Url.Content(@"~/Content/Images/test.jpg")" width="100%" height="200px" class="img-fluid" alt="Responsive image"></code></pre>

<figure class="highlight">
    <pre><code class="language-scss" data-lang="scss"><span class="c1">// Extra small devices (portrait phones, less than 576px)</span>
    <span class="c1">// No media query since this is the default in Bootstrap</span>
    <span class="c1">// Small devices (landscape phones, 576px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">576px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Medium devices (tablets, 768px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">768px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Large devices (desktops, 992px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">992px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Extra large devices (large desktops, 1200px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">1200px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>
</code></pre>
</figure>
<div class="alert alert-danger" role="alert">
    This is a danger alert—check it out!
</div>
<p>Welcome</p>
<figure class="highlight">
    <pre><code class="language-scss" data-lang="scss"><span class="c1">// Extra small devices (portrait phones, less than 576px)</span>
    <span class="c1">// No media query since this is the default in Bootstrap</span>

    <span class="c1">// Small devices (landscape phones, 576px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">576px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Medium devices (tablets, 768px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">768px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Large devices (desktops, 992px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">992px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span>

    <span class="c1">// Extra large devices (large desktops, 1200px and up)</span>
    <span class="k"></span> <span class="p">(</span><span class="n">min-width</span><span class="o">:</span> <span class="m">1200px</span><span class="p">)</span> <span class="p">{</span> <span class="nc">...</span> <span class="p">}</span></code></pre>
</figure>

<p>Since we write our source CSS in Sass, all our media queries are available via Sass mixins:</p>

@using (Html.BeginForm("FormMethod", "IT", FormMethod.Post))
{
    <h3>@ViewBag.Go</h3>
}

@using (Html.BeginForm("FormMethod", "IT", FormMethod.Post))
{
    <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" name="name" id="name" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Password">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <!--<li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>-->
                    <li>@Html.ActionLink("Outils IT", "ITTools", "IT")</li>
                    <li>@Html.ActionLink("Documentation", "ITTools", "IT")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>